services:
  - type: web
    name: personal-finance-manager
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: finance_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: root
